### ISSUE TITLE
There is no way to thank you for such an amazing app!

### ISSUE THREAD

**Issue by Barbacoa08** [khromov/appreciation-jar#3]
As a very happy user of Appreciation Jar's Android app and Web app, I would like to be able to send you a thank you.

[Buy Me a Coffee](https://www.buymeacoffee.com/) is a common one I see on side projects. Or a link to your Venmo/PayPal/CashApp/whichever would also work. However works for you, I as an extremely happy user would like to buy you a coffee/beer/sandwich/flowers/small-happiness.

**Comment by khromov** [comment]
Hi @Barbacoa08 

Thanks for reaching out and for being one of the first users of the app! 🌞

Since you wrote that you use the Android app, the best way to help right now would be to leave a review so that the app gets a bit more visibility!
https://play.google.com/store/apps/details?id=place.appreciation.jar

If you have any ideas or other feedback there's an email inside the app under Settings > Help and Support.

Thanks again for your feedback, even knowing that the app reached one person makes me happy!

**Comment by Barbacoa08** [comment]
Done! I've also suggested Appreciation Jar to a few friends and asked them to review it in their app store. Thanks again for making this and I hope to see it's popularity explode!
